# [START runtime]
runtime: nodejs
env: flex
# [END runtime]

# [START handlers]
handlers:
 - url: /
   static_files: build/index.html
   upload: build/index.html

 - url: /(.*)
   static_files: build/\1
   upload: build/(.*)
# [END handlers]

#[cloud sql connection]
beta_settings:
  cloud_sql_instances: where-should-we--1577491661730:us-central1:marsupials

# cloud sql connection variables
env_variables:
  DB_USER: root
  DB_PASS: Koalasrule!
  DB_NAME: wswe
  DB_HOST: 35.225.190.208
  # e.g. my-awesome-project:us-central1:my-cloud-sql-instance
  CLOUD_SQL_CONNECTION_NAME: where-should-we--1577491661730:us-central1:marsupials
  MYSQL_DSN: mysql:unix_socket=/cloudsql/where-should-we--1577491661730:us-central1:marsupials;dbname=wswe
  MYSQL_USER: root
  MYSQL_PASSWORD: Koalasrule!