# [START runtime]
runtime: nodejs
env: flex
# [END runtime]

# [START handlers]
handlers:
 - url: /
   static_files: build/index.html
   upload: build/index.html

 - url: /(.*)
   static_files: build/\1
   upload: build/(.*)
# [END handlers]

#[cloud sql connection]
beta_settings:
  cloud_sql_instances: where-should-we--1577491661730:us-central1:marsupials

# cloud sql connection variables
env_variables:
  DB_USER: marsupials
  DB_PASS: OxItt8JK6mNvrzj6
  DB_NAME: wswe
  # e.g. my-awesome-project:us-central1:my-cloud-sql-instance
  CLOUD_SQL_CONNECTION_NAME: where-should-we--1577491661730:us-central1:marsupials